version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: netlify-cli
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.10
    - 3.10.11
    - 3.10.12
    - 3.10.2
    - 3.10.3
    - 3.10.4
    - 3.10.5
    - 3.10.6
    - 3.10.7
    - 3.10.8
    - 3.10.9
    - 3.11.0
    - 3.11.1
    - 3.12.0
    - 3.13.0
    - 3.13.1
    - 3.13.10
    - 3.13.2
    - 3.13.3
    - 3.13.4
    - 3.13.5
    - 3.13.6
    - 3.13.7
    - 3.13.8
    - 3.13.9
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.16.0
    - 3.16.1
    - 3.16.2
    - 3.17.0
    - 3.17.1
    - 3.17.2
    - 3.18.0
    - 3.18.2
    - 3.19.0
    - 3.19.1
    - 3.20.0
    - 3.20.1
    - 3.21.10
    - 3.21.11
    - 3.21.13
    - 3.21.2
    - 3.21.3
    - 3.21.4
    - 3.21.5
    - 3.21.6
    - 3.21.7
    - 3.21.8
    - 3.21.9
    - 3.22.0
    - 3.23.0
    - 3.23.1
    - 3.23.3
    - 3.24.0
    - 3.24.1
    - 3.4.6
    - 3.4.7
    - 3.4.8
    - 3.5.0
    - 3.6.0
    - 3.7.0
    - 3.7.1
    - 3.8.0
    - 3.8.1
    - 3.8.2
    - 3.8.3
    - 3.8.4
    - 3.8.5
    - 3.8.6
    - 3.9.0
  - dependency-name: gatsby
    versions:
    - 2.32.9
    - 3.3.0
  - dependency-name: commitlint-config-dsmjs
    versions:
    - 1.0.25
  - dependency-name: husky
    versions:
    - 5.1.2
  - dependency-name: "@dsmjs/eslint-config"
    versions:
    - 1.0.61
    - 1.0.62
    - 1.0.64
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: gatsby-remark-autolink-headers
    versions:
    - 2.10.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 3.12.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: gatsby-plugin-netlify
    versions:
    - 2.10.0
  - dependency-name: gatsby-plugin-glamor
    versions:
    - 2.9.0
  - dependency-name: gatsby-link
    versions:
    - 2.10.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
