repository:
  description: Gatsby site that is a WIP to replace the previous Jekyll site
  homepage: https://dsmjs.netlify.com/
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
labels:
  - name: bug
    color: ee0701
  - name: duplicate
    color: cccccc
  - name: enhancement
    color: 84b6eb
  - name: help wanted
    color: 128A0C
  - name: invalid
    color: e6e6e6
  - name: question
    color: cc317c
  - name: wontfix
    color: ffffff
  - name: greenkeeper
    color: 00c775
  - name: feature parity with legacy site
    color: 5146f2
  - name: feature missing from old site
    color: 8eedd0
  - name: good first issue
    color: 7057ff
  - name: semantic-release
    color: ededed
  - name: security
    color: f7de00
